# Generated by Django 5.0.3 on 2024-03-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnails',
            field=models.ImageField(default=0, upload_to='images/thumbnails'),
            preserve_default=False,
        ),
    ]
